---
volumes:
  tf-data: {}
  infra-secrets: {}
services:
  terraform:
    image: hashicorp/terraform:1.7.5
    volumes:
      - $PWD/infra:/infra
      - tf-data:/tf-data
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - TERRAFORM_STATE_S3_BUCKET
      - TERRAFORM_STATE_S3_KEY
      - TF_DATA_DIR=/tf-data
      - TF_IN_AUTOMATION="true"
  configure-database:
    build:
      dockerfile: ansible.Dockerfile
      context: .
    volumes:
      - infra-secrets:/secrets
      - $PWD/config:/config
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=false
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - POSTGRES_VERSION
    entrypoint: sh
    command:
      - -c
      - |
        ansible-playbook -i $(cat /secrets/db_host), \
          -e login_user=$(cat /secrets/db_user) \
          -e db_user=$(cat /secrets/db_db_user) \
          -e db_password=$(cat /secrets/db_db_password) \
          -e db_name=$(cat /secrets/db_name) \
          -e db_backup_bucket_name=$(cat /secrets/db_backup_bucket) \
          --private-key /secrets/db_key \
          --extra-vars @/config/vars.yaml \
          /config/database.yml
  test-infra:
    build:
      dockerfile: bats.Dockerfile
      context: .
    environment:
      - DB_HOST
      - DB_USER
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - AWS_DEFAULT_REGION
    volumes:
      - infra-secrets:/secrets
      - $PWD/tests:/tests
    command:
      - /tests
  terraform-init:
    depends_on:
      ensure-required-env-vars-set:
        condition: service_completed_successfully
      ensure-logged-into-aws:
        condition: service_completed_successfully
      create-tf-state-bucket:
        condition: service_completed_successfully
    image: hashicorp/terraform:1.7.5
    volumes:
      - $PWD/infra:/infra
      - tf-data:/tf-data
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - REINIT
      - TERRAFORM_STATE_S3_BUCKET
      - TERRAFORM_STATE_S3_KEY
      - TF_DATA_DIR=/tf-data
      - TF_IN_AUTOMATION="true"
    entrypoint: sh
    command:
      - -c
      - |-
        { test -z "$REINIT" && test -f "/tf-data/.initialized"; } && exit 0
        terraform init  \
          -backend-config=bucket=$TERRAFORM_STATE_S3_BUCKET \
          -backend-config=key=$TERRAFORM_STATE_S3_KEY \
          -backend-config=region=$AWS_REGION && touch /tf-data/.initialized
  ensure-logged-into-aws:
    image: amazon/aws-cli:2.2.9
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - TERRAFORM_STATE_S3_BUCKET
    entrypoint: sh
    command:
      - -c
      - "aws sts get-caller-identity &>/dev/null"
  create-tf-state-bucket:
    image: amazon/aws-cli:2.2.9
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
      - TERRAFORM_STATE_S3_BUCKET
    entrypoint: sh
    command:
      - -c
      - |-
        aws s3 ls s3://$TERRAFORM_STATE_S3_BUCKET || aws s3 mb s3://$TERRAFORM_STATE_S3_BUCKET
  ensure-required-env-vars-set:
    image: bash:5
    environment:
      - TERRAFORM_STATE_S3_BUCKET
      - TERRAFORM_STATE_S3_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
    command:
      - -c
      - |-
        for required in TERRAFORM_STATE_S3_BUCKET TERRAFORM_STATE_S3_KEY \
          AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN AWS_DEFAULT_REGION;
        do \
          set -x
          if test -z "$${!required}"
          then
            >&2 echo "ERROR: Please define $$required"
            exit 1
          fi
        done
  write-infra-secrets:
    image: hashicorp/terraform:1.7.5
    volumes:
      - $PWD/infra:/infra
      - tf-data:/tf-data
      - infra-secrets:/secrets
    working_dir: /infra
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - TERRAFORM_STATE_S3_BUCKET
      - TERRAFORM_STATE_S3_KEY
      - TF_DATA_DIR=/tf-data
      - TF_IN_AUTOMATION="true"
    entrypoint: sh
    # TODO: DRY this up.
    command:
      - -c
      - |-
        terraform output -raw wiz_interview_db_ssh_private_key > /secrets/db_key && chmod 600 /secrets/db_key &&
        terraform output -raw wiz_interview_db_dns_record > /secrets/db_host &&
        terraform output -raw wiz_interview_db_login_user > /secrets/db_user &&
        terraform output -raw wiz_interview_db_db_user > /secrets/db_db_user &&
        terraform output -raw wiz_interview_db_name > /secrets/db_name &&
        terraform output -raw wiz_interview_db_db_password > /secrets/db_db_password &&
        terraform output -raw wiz_interview_db_backup_bucket > /secrets/db_backup_bucket &&
        terraform output -raw wiz_interview_test_machine_ssh_private_key > /secrets/test_machine_key && chmod 600 /secrets/test_machine_key &&
        terraform output -raw wiz_interview_test_machine_dns_record > /secrets/test_machine_host &&
        terraform output -raw wiz_interview_test_machine_login_user > /secrets/test_machine_user &&
        terraform output -raw wiz_interview_test_machine_private_ip > /secrets/test_machine_private_ip
  delete-infra-secrets:
    image: bash:5
    volumes:
      - infra-secrets:/secrets
    command:
      - -c
      - rm -f /secrets/*
  ssh-into-db:
    build:
      dockerfile: ansible.Dockerfile
      context: .
    volumes:
      - infra-secrets:/secrets
    entrypoint: sh
    command:
      - -c
      - |-
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
          -i /secrets/db_key \
          $(cat /secrets/db_user)@$(cat /secrets/db_host)
