apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
data:
  database_uri: {{ .Values.database.uri | b64enc }}
  database_type: {{ .Values.database.type | b64enc }}
