---
# Tasks shamelessly stolen from: https://gist.github.com/greenhat/11785194cbdc90624b67
- name: Configure database
  hosts: all
  gather_facts: false
  remote_user: "{{ login_user }}"
  tasks:
    - name: Install PostgreSQL and acl (so that Ansible can configure a db user)
      become: true
      apt:
        update_cache: true
        name:
          - "postgresql-{{ postgres_version }}"
          - libpq-dev
          - python3-dev
          - python3-psycopg2
        state: present

    - name: Allow connectivity on all interfaces
      become: true
      lineinfile:
        dest: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
        regexp: "listen_addresses ="
        line: "listen_addresses = '*'"
        state: present

    - name: Set password for postgres user
      become: true
      become_user: postgres
      command: psql -c "ALTER USER postgres PASSWORD '{{ db_password }}'"

    - name: Create user
      become: true
      become_user: postgres
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"

    - name: Create app database
      become: true
      become_user: postgres
      postgresql_db:
        owner: "{{ db_user }}"
        name: "{{ db_name }}"
